package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_itf_ar_interface")
public class ItfArInterface extends BaseDTO {

     public static final String FIELD_AR_INTERFACE_ID = "arInterfaceId";
     public static final String FIELD_ACCOUNTING_STATUS = "accountingStatus";
     public static final String FIELD_ACCOUNTING_DATE = "accountingDate";
     public static final String FIELD_ACCOUNTING_REMARK = "accountingRemark";
     public static final String FIELD_UNIQUE_CODE = "uniqueCode";
     public static final String FIELD_APPLY_NUM = "applyNum";
     public static final String FIELD_CONTRACT_START_DATE = "contractStartDate";
     public static final String FIELD_CUSTOMER_NAME = "customerName";
     public static final String FIELD_PROD_SCHEME_NAME = "prodSchemeName";
     public static final String FIELD_LEASE_TYPE = "leaseType";
     public static final String FIELD_LEASE_COMPANY = "leaseCompany";
     public static final String FIELD_SUB_COMPANY = "subCompany";
     public static final String FIELD_SERIAL_NUMBER = "serialNumber";
     public static final String FIELD_SCHEDULED_REPAYMENT_DATE = "scheduledRepaymentDate";
     public static final String FIELD_INCOME_PERIOD = "incomePeriod";
     public static final String FIELD_RENTAL_INCOME_I1 = "rentalIncomeI1";
     public static final String FIELD_RENTAL_INCOME_I2 = "rentalIncomeI2";
     public static final String FIELD_RECE_PRINCIPAL = "recePrincipal";
     public static final String FIELD_RECE_INTEREST_I1 = "receInterestI1";
     public static final String FIELD_RECE_INTEREST_I2 = "receInterestI2";
     public static final String FIELD_PREPAID_RENT_PER_PERIOD = "prepaidRentPerPeriod";
     public static final String FIELD_SHALL_CARRY_INTEREST = "shallCarryInterest";
     public static final String FIELD_POST_FEE = "postFee";
     public static final String FIELD_SERVICE_CHARGE_I1 = "serviceChargeI1";
     public static final String FIELD_SERVICE_CHARGE_I2 = "serviceChargeI2";
     public static final String FIELD_PRINCIPAL_TAX = "principalTax";
     public static final String FIELD_INCOME_TAX = "incomeTax";
     public static final String FIELD_PRINCIPAL_BALANCE = "principalBalance";
     public static final String FIELD_SERVICE_CHARGE_FUNCTION = "serviceChargeFunction";
     public static final String FIELD_PAYMENT_STATUS = "paymentStatus";
     public static final String FIELD_OVERDUE_START_DATE = "overdueStartDate";
     public static final String FIELD_OVERDUE_DAYS = "overdueDays";
     public static final String FIELD_OVERDUE_90_DATE = "overdue90Date";
     public static final String FIELD_COLLECT_DATE = "collectDate";
     public static final String FIELD_CONTRACT_STATUS = "contractStatus";
     public static final String FIELD_SHOULD_INCOME = "shouldIncome";
     public static final String FIELD_SOURCE_VEHICLE = "sourceVehicle";
     public static final String FIELD_INVOICE_ENTITY = "invoiceEntity";
     public static final String FIELD_ACC_ENTITY = "accEntity";
     public static final String FIELD_ACTUAL_INCOME = "actualIncome";
     public static final String FIELD_SUB_COM_VALUE = "subComValue";
     public static final String FIELD_BELONG_COM_VALUE = "belongComValue";
     public static final String FIELD_INVOICE_COM_VALUE = "invoiceComValue";

     public static final String FIELD_ACTUAL_MONTHLY_INCOME = "actualMonthlyIncome";
     public static final String FIELD_ACTUAL_CARRY_INTEREST = "actualCarryInterest";
     public static final String FIELD_ACTUAL_SERVICE_CHARGE = "actualServiceCharge";


    @Id
    @GeneratedValue
    private Long arInterfaceId; //表ID，主键，供其他表做外键

    @Length(max = 30)
    private String accountingStatus; //入账状态

    private Date accountingDate; //入账日期

    @Length(max = 255)
    private String accountingRemark; //入账消息（如凭证编号等，可以考虑是否需要多个）

    @Length(max = 255)
    private String uniqueCode; //唯一标识

    @Transient
    private Long sourceIterfaceId; // 用作更新的字段

    @Length(max = 255)
    private String applyNum; //申请编号

    @Length(max = 255)
    private String contractStartDate; //合同生效日期

    @Length(max = 255)
    private String customerName; //客户名称

    @Length(max = 255)
    private String prodSchemeName; //产品名称

    @Length(max = 255)
    private String leaseType; //租赁类型

    @Length(max = 255)
    private String leaseCompany; //租赁公司

    @Length(max = 255)
    private String subCompany; //分公司

    @Length(max = 10)
    private String serialNumber; //分期序号

    @Length(max = 255)
    private String scheduledRepaymentDate; //计划还款日期

    @Length(max = 255)
    private String incomePeriod; //收入归属期间

    @Length(max = 255)
    private String rentalIncomeI1; //经租本期应提租金收入I1

    @Length(max = 255)
    private String rentalIncomeI2; //经租本期应提租金收入I12

    @Length(max = 255)
    private String recePrincipal; //每期月供本金

    @Length(max = 255)
    private String receInterestI1; //本期应提利息收入I1

    @Length(max = 255)
    private String receInterestI2; //本期应提利息收入I2

    @Length(max = 255)
    private String prepaidRentPerPeriod; //预付租金每期摊销金额

    @Length(max = 255)
    private String shallCarryInterest; //本期应提贴息

    @Length(max = 255)
    private String postFee; //本期应提贴手续费

    @Length(max = 255)
    private String serviceChargeI1; //本期应提手续费I1

    @Length(max = 255)
    private String serviceChargeI2; //本期应提手续费I2

    @Length(max = 255)
    private String principalTax; //本期本金税金

    @Length(max = 255)
    private String incomeTax; //本期收入税金

    @Length(max = 255)
    private String principalBalance; //本金余额

    @Length(max = 255)
    private String serviceChargeFunction; //手续费收取方式

    @Length(max = 255)
    private String paymentStatus; //还款状态

    @Length(max = 255)
    private String overdueStartDate; //逾期起始日期

    @Length(max = 255)
    private String overdueDays; //逾期天数

    @Length(max = 255)
    private String overdue90Date; //逾期第90天日期

    @Length(max = 255)
    private String collectDate; //收车日期

    @Length(max = 255)
    private String contractStatus; //合同状态

    @Length(max = 255)
    private String applyStatus; //申请状态

    @Length(max = 255)
    private String shouldIncome; //本期应提收入

    @Length(max = 255)
    private String sourceVehicle; //是否资源车

    @Length(max = 255)
    private String invoiceEntity; //发票主体

    @Length(max = 255)
    private String accEntity; //记账主体

    @Length(max = 255)
    private String actualIncome; //本期实提收入

    @Length(max = 255)
    private String subComValue; //分公司段

    @Length(max = 255)
    private String belongComValue; //所属公司段

    @Length(max = 255)
    private String invoiceComValue; //发票主体


    @Length(max = 255)
    private String actualMonthlyIncome; //实提月供收入

    @Length(max = 255)
    private String actualCarryInterest; //实提贴息

    @Length(max = 255)
    private String actualServiceCharge; //实提手续费

    public String getActualMonthlyIncome() {
        return actualMonthlyIncome;
    }

    public void setActualMonthlyIncome(String actualMonthlyIncome) {
        this.actualMonthlyIncome = actualMonthlyIncome;
    }

    public String getActualCarryInterest() {
        return actualCarryInterest;
    }

    public void setActualCarryInterest(String actualCarryInterest) {
        this.actualCarryInterest = actualCarryInterest;
    }

    public String getActualServiceCharge() {
        return actualServiceCharge;
    }

    public void setActualServiceCharge(String actualServiceCharge) {
        this.actualServiceCharge = actualServiceCharge;
    }

    public Long getArInterfaceId() {
        return arInterfaceId;
    }

    public void setArInterfaceId(Long arInterfaceId) {
        this.arInterfaceId = arInterfaceId;
    }

    public void setAccountingStatus(String accountingStatus){
        this.accountingStatus = accountingStatus;
    }

    public String getAccountingStatus(){
        return accountingStatus;
    }

    public void setAccountingDate(Date accountingDate){
        this.accountingDate = accountingDate;
    }

    public Date getAccountingDate(){
        return accountingDate;
    }

    public void setAccountingRemark(String accountingRemark){
        this.accountingRemark = accountingRemark;
    }

    public String getAccountingRemark(){
        return accountingRemark;
    }

    public void setUniqueCode(String uniqueCode){
        this.uniqueCode = uniqueCode;
    }

    public String getUniqueCode(){
        return uniqueCode;
    }

    public void setApplyNum(String applyNum){
        this.applyNum = applyNum;
    }

    public String getApplyNum(){
        return applyNum;
    }

    public void setContractStartDate(String contractStartDate){
        this.contractStartDate = contractStartDate;
    }

    public String getContractStartDate(){
        return contractStartDate;
    }

    public void setCustomerName(String customerName){
        this.customerName = customerName;
    }

    public String getCustomerName(){
        return customerName;
    }

    public void setProdSchemeName(String prodSchemeName){
        this.prodSchemeName = prodSchemeName;
    }

    public String getProdSchemeName(){
        return prodSchemeName;
    }

    public void setLeaseType(String leaseType){
        this.leaseType = leaseType;
    }

    public String getLeaseType(){
        return leaseType;
    }

    public void setLeaseCompany(String leaseCompany){
        this.leaseCompany = leaseCompany;
    }

    public String getLeaseCompany(){
        return leaseCompany;
    }

    public void setSubCompany(String subCompany){
        this.subCompany = subCompany;
    }

    public String getSubCompany(){
        return subCompany;
    }

    public void setSerialNumber(String serialNumber){
        this.serialNumber = serialNumber;
    }

    public String getSerialNumber(){
        return serialNumber;
    }

    public void setScheduledRepaymentDate(String scheduledRepaymentDate){
        this.scheduledRepaymentDate = scheduledRepaymentDate;
    }

    public String getScheduledRepaymentDate(){
        return scheduledRepaymentDate;
    }

    public void setIncomePeriod(String incomePeriod){
        this.incomePeriod = incomePeriod;
    }

    public String getIncomePeriod(){
        return incomePeriod;
    }

    public void setRentalIncomeI1(String rentalIncomeI1){
        this.rentalIncomeI1 = rentalIncomeI1;
    }

    public String getRentalIncomeI1(){
        return rentalIncomeI1;
    }

    public void setRentalIncomeI2(String rentalIncomeI2){
        this.rentalIncomeI2 = rentalIncomeI2;
    }

    public String getRentalIncomeI2(){
        return rentalIncomeI2;
    }

    public void setRecePrincipal(String recePrincipal){
        this.recePrincipal = recePrincipal;
    }

    public String getRecePrincipal(){
        return recePrincipal;
    }

    public void setReceInterestI1(String receInterestI1){
        this.receInterestI1 = receInterestI1;
    }

    public String getReceInterestI1(){
        return receInterestI1;
    }

    public void setReceInterestI2(String receInterestI2){
        this.receInterestI2 = receInterestI2;
    }

    public String getReceInterestI2(){
        return receInterestI2;
    }

    public void setPrepaidRentPerPeriod(String prepaidRentPerPeriod){
        this.prepaidRentPerPeriod = prepaidRentPerPeriod;
    }

    public String getPrepaidRentPerPeriod(){
        return prepaidRentPerPeriod;
    }

    public void setShallCarryInterest(String shallCarryInterest){
        this.shallCarryInterest = shallCarryInterest;
    }

    public String getShallCarryInterest(){
        return shallCarryInterest;
    }

    public void setPostFee(String postFee){
        this.postFee = postFee;
    }

    public String getPostFee(){
        return postFee;
    }

    public void setServiceChargeI1(String serviceChargeI1){
        this.serviceChargeI1 = serviceChargeI1;
    }

    public String getServiceChargeI1(){
        return serviceChargeI1;
    }

    public void setServiceChargeI2(String serviceChargeI2){
        this.serviceChargeI2 = serviceChargeI2;
    }

    public String getServiceChargeI2(){
        return serviceChargeI2;
    }

    public void setPrincipalTax(String principalTax){
        this.principalTax = principalTax;
    }

    public String getPrincipalTax(){
        return principalTax;
    }

    public void setIncomeTax(String incomeTax){
        this.incomeTax = incomeTax;
    }

    public String getIncomeTax(){
        return incomeTax;
    }

    public void setPrincipalBalance(String principalBalance){
        this.principalBalance = principalBalance;
    }

    public String getPrincipalBalance(){
        return principalBalance;
    }

    public void setServiceChargeFunction(String serviceChargeFunction){
        this.serviceChargeFunction = serviceChargeFunction;
    }

    public String getServiceChargeFunction(){
        return serviceChargeFunction;
    }

    public void setPaymentStatus(String paymentStatus){
        this.paymentStatus = paymentStatus;
    }

    public String getPaymentStatus(){
        return paymentStatus;
    }

    public void setOverdueStartDate(String overdueStartDate){
        this.overdueStartDate = overdueStartDate;
    }

    public String getOverdueStartDate(){
        return overdueStartDate;
    }

    public void setOverdueDays(String overdueDays){
        this.overdueDays = overdueDays;
    }

    public String getOverdueDays(){
        return overdueDays;
    }

    public void setOverdue90Date(String overdue90Date){
        this.overdue90Date = overdue90Date;
    }

    public String getOverdue90Date(){
        return overdue90Date;
    }

    public void setCollectDate(String collectDate){
        this.collectDate = collectDate;
    }

    public String getCollectDate(){
        return collectDate;
    }

    public void setContractStatus(String contractStatus){
        this.contractStatus = contractStatus;
    }

    public String getContractStatus(){
        return contractStatus;
    }

    public void setApplyStatus(String applyStatus){
        this.applyStatus = applyStatus;
    }

    public String getApplyStatus(){
        return applyStatus;
    }

    public void setShouldIncome(String shouldIncome){
        this.shouldIncome = shouldIncome;
    }

    public String getShouldIncome(){
        return shouldIncome;
    }

    public void setSourceVehicle(String sourceVehicle){
        this.sourceVehicle = sourceVehicle;
    }

    public String getSourceVehicle(){
        return sourceVehicle;
    }

    public void setInvoiceEntity(String invoiceEntity){
        this.invoiceEntity = invoiceEntity;
    }

    public String getInvoiceEntity(){
        return invoiceEntity;
    }

    public void setAccEntity(String accEntity){
        this.accEntity = accEntity;
    }

    public String getAccEntity(){
        return accEntity;
    }

    public void setActualIncome(String actualIncome){
        this.actualIncome = actualIncome;
    }

    public String getActualIncome(){
        return actualIncome;
    }

    public void setSubComValue(String subComValue){
        this.subComValue = subComValue;
    }

    public String getSubComValue(){
        return subComValue;
    }

    public void setBelongComValue(String belongComValue){
        this.belongComValue = belongComValue;
    }

    public String getBelongComValue(){
        return belongComValue;
    }

    public void setInvoiceComValue(String invoiceComValue){
        this.invoiceComValue = invoiceComValue;
    }

    public String getInvoiceComValue(){
        return invoiceComValue;
    }

    public Long getSourceIterfaceId() {
        return sourceIterfaceId;
    }

    public void setSourceIterfaceId(Long sourceIterfaceId) {
        this.sourceIterfaceId = sourceIterfaceId;
    }

     }
