package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_itf_contract_validated")
public class ItfContractValidated extends BaseDTO {

     public static final String FIELD_CONTRACT_VALIDATED_ID = "contractValidatedId";
     public static final String FIELD_ACCOUNTING_STATUS = "accountingStatus";
     public static final String FIELD_ACCOUNTING_DATE = "accountingDate";
     public static final String FIELD_ACCOUNTING_REMARK = "accountingRemark";
     public static final String FIELD_BATCH_NUM = "batchNum";
     public static final String FIELD_SOURCE_SYSTEM = "sourceSystem";
     public static final String FIELD_UNIQUE_CODE = "uniqueCode";
     public static final String FIELD_INVOICE_ENTITY_VALUE = "invoiceEntityValue";
     public static final String FIELD_SUBCOM_VALUE = "subcomValue";
     public static final String FIELD_APPLY_NUM = "applyNum";
     public static final String FIELD_CONTRACT_NUM = "contractNum";
     public static final String FIELD_APPLY_TYPE = "applyType";
     public static final String FIELD_CUSTOMER_NAME = "customerName";
     public static final String FIELD_SOURCE_VEHICLE = "sourceVehicle";
     public static final String FIELD_SOURCE_VEHICLE_TYPE = "sourceVehicleType";
     public static final String FIELD_LEASING_TYPE = "leasingType";
     public static final String FIELD_APPLY_STATUS = "applyStatus";
     public static final String FIELD_CONTRACT_STATUS = "contractStatus";
     public static final String FIELD_VEHICLE_PRICE = "vehiclePrice";
     public static final String FIELD_VRHICLE_IDENTIFY_NUM = "vrhicleIdentifyNum";
     public static final String FIELD_BRAND_AMOUNT = "brandAmount";
     public static final String FIELD_PURCHASINGTAX_INVOICE_AMOUNT = "purchasingtaxInvoiceAmount";
     public static final String FIELD_PRE_RENT_AMOUNT = "preRentAmount";
     public static final String FIELD_INVEST_AMOUNT = "investAmount";
     public static final String FIELD_FIN_AMOUNT = "finAmount";
     public static final String FIELD_FIN_LEASE_VRHICLE = "finLeaseVrhicle";
     public static final String FIELD_FIN_LEASE_BUSINSURANCE = "finLeaseBusinsurance";
     public static final String FIELD_FIN_LEASE_SPINSURANCE = "finLeaseSpinsurance";
     public static final String FIELD_FIN_LEASE_PURCHASINGTAX = "finLeasePurchasingtax";
     public static final String FIELD_FIN_LEASE_VEHICLEVESSEL_TAX = "finLeaseVehiclevesselTax";
     public static final String FIELD_FIN_LEASE_GPS = "finLeaseGps";
     public static final String FIELD_FIN_LEASE_ACCOUNTINSURANCE = "finLeaseAccountinsurance";
     public static final String FIELD_FIN_LEASE_ADDCOSTINSURANCE = "finLeaseAddcostinsurance";
     public static final String FIELD_FIN_LEASE_AFTSER_CHARGE = "finLeaseAftserCharge";
     public static final String FIELD_ACC_MANAGE_EXPENSE = "accManageExpense";
     public static final String FIELD_OUTPUT_TAX = "outputTax";
     public static final String FIELD_VEHICLE_INCOME = "vehicleIncome";
     public static final String FIELD_DOWN_PAYMENT_OUTPUT = "downPaymentOutput";
     public static final String FIELD_PURCHASINGTAX_TAX = "purchasingtaxTax";
     public static final String FIELD_BUSINSURANCE_TAX = "businsuranceTax";
     public static final String FIELD_SPINSUR_TAX = "spinsurTax";
     public static final String FIELD_FIN_LEASE_GPSTAX = "finLeaseGpstax";
     public static final String FIELD_VRHICLE_INVOICE_NOTAX = "vrhicleInvoiceNotax";
     public static final String FIELD_BUSINSURANCE_INVAMO_NOTAX = "businsuranceInvamoNotax";
     public static final String FIELD_FIN_LEASE_SPINSUR_INVOICE = "finLeaseSpinsurInvoice";
     public static final String FIELD_PURCHASINGTAX_INVAMO_NOTAX = "purchasingtaxInvamoNotax";
     public static final String FIELD_VEHICLEVESSELTAX_INVOICE = "vehiclevesseltaxInvoice";
     public static final String FIELD_ACCOUNTINSURANCE_INVOICE_NOTAX = "accountinsuranceInvoiceNotax";
     public static final String FIELD_ACC_MANAGE_EXPENSE_INVOICE = "accManageExpenseInvoice";
     public static final String FIELD_VRHICLE_INVOICE_TAX = "vrhicleInvoiceTax";
     public static final String FIELD_BUSINSURANCE_INVOICE_TAX = "businsuranceInvoiceTax";
     public static final String FIELD_SPINSUR_INVOICE_TAX = "spinsurInvoiceTax";
     public static final String FIELD_PURCHASINGTAX_INVOICE_TAX = "purchasingtaxInvoiceTax";
     public static final String FIELD_ACCOUNTINSURANCE_INVOICE_TAX = "accountinsuranceInvoiceTax";
     public static final String FIELD_LONGTERM_RECE_PRINCIPAL = "longtermRecePrincipal";
     public static final String FIELD_PRINCIPAL_OUTPUT = "principalOutput";
     public static final String FIELD_LONGTERM_RECE_INTEREST = "longtermReceInterest";
     public static final String FIELD_CUSTOMER_RATE = "customerRate";
     public static final String FIELD_CLEARING_RATE = "clearingRate";
     public static final String FIELD_DOWN_PAYMENT_AMOUNT = "downPaymentAmount";
     public static final String FIELD_FINAL_PAYMENT_AMOUNT = "finalPaymentAmount";
     public static final String FIELD_SERVICE_CHARGE_CUSTOMER = "serviceChargeCustomer";
     public static final String FIELD_MARGIN_AMOUNT = "marginAmount";
     public static final String FIELD_PERPERIOD_CUSTOMER_RENT = "perperiodCustomerRent";
     public static final String FIELD_ROBBERY_SECURITY_AMOUNT = "robberySecurityAmount";
     public static final String FIELD_DISCOUNT_AMOUNT = "discountAmount";
     public static final String FIELD_GPS_BASIC_PRICE = "gpsBasicPrice";
     public static final String FIELD_GPS_RAISE_PRICE = "gpsRaisePrice";
     public static final String FIELD_GPS_SERVICE_CHARGE = "gpsServiceCharge";
     public static final String FIELD_EXTENDED_WARRANTY_AMOUNT = "extendedWarrantyAmount";
     public static final String FIELD_LOAN_AMOUNT = "loanAmount";
     public static final String FIELD_RESIDUAL_PRINCIPAL = "residualPrincipal";
     public static final String FIELD_MARGIN_MATCH = "marginMatch";
     public static final String FIELD_MANUFACTURER_DISCOUNT_AMOUNT = "manufacturerDiscountAmount";
     public static final String FIELD_AGENCY_DISCOUNT_AMOUNT = "agencyDiscountAmount";
     public static final String FIELD_DETU_MANUF_DISCOUNT_AMOUNT = "detuManufDiscountAmount";
     public static final String FIELD_DETU_AGENCY_DISCOUNT_AMOUNT = "detuAgencyDiscountAmount";
     public static final String FIELD_WHETHER_DISCOUNT = "whetherDiscount";
     public static final String FIELD_EXTRA_SERVICE_CHARGE = "extraServiceCharge";
     public static final String FIELD_ACTUAL_SERVICE_CHARGE = "actualServiceCharge";
     public static final String FIELD_EXTRA_DISCOUNT_AMOUNT = "extraDiscountAmount";
     public static final String FIELD_ACTUAL_DISCOUNT_AMOUNT = "actualDiscountAmount";
     public static final String FIELD_BELONGCOM_VALUE = "belongcomValue";
     public static final String FIELD_CONTRACT_START_DATE = "contractStartDate";
     public static final String FIELD_CONTRACT_END_DATE = "contractEndDate";


     @Id
     @GeneratedValue
     private Long contractValidatedId; //表ID，主键，供其他表做外键

     @Length(max = 30)
     private String accountingStatus; //入账状态

     private Date accountingDate; //入账日期

     @Length(max = 200)
     private String accountingRemark; //入账消息（如凭证编号等，可以考虑是否需要多个）

     @Length(max = 200)
     private String batchNum; //批次号

     @Length(max = 200)
     private String sourceSystem; //来源系统

     @Length(max = 200)
     private String uniqueCode; //唯一标识

     @Length(max = 200)
     private String invoiceEntityValue; //发票主体公司段值

     @Length(max = 200)
     private String subcomValue; //分公司公司段值

     @Length(max = 200)
     private String applyNum; //申请编号

     @Length(max = 200)
     private String contractNum; //合同号

     @Length(max = 200)
     private String applyType; //申请类型

     @Length(max = 200)
     private String customerName; //客户名称

     @Length(max = 200)
     private String sourceVehicle; //是否资源车

     @Length(max = 200)
     private String sourceVehicleType; //资源车类型

     @Length(max = 200)
     private String leasingType; //租赁类型

     @Length(max = 200)
     private String applyStatus; //申请状态

     @Length(max = 200)
     private String contractStatus; //合同状态

     private BigDecimal vehiclePrice; //车辆销售价

     @Length(max = 200)
     private String vrhicleIdentifyNum; //车架号

     private BigDecimal brandAmount; //上牌费金额

     private BigDecimal purchasingtaxInvoiceAmount; //购置税发票金额

     private BigDecimal preRentAmount; //预付租金金额

     private BigDecimal investAmount; //投资总额

     private BigDecimal finAmount; //融资额

     private BigDecimal finLeaseVrhicle; //融资租赁项车款

     private BigDecimal finLeaseBusinsurance; //融资租赁项商业保险

     private BigDecimal finLeaseSpinsurance; //融资租赁项交强保险

     private BigDecimal finLeasePurchasingtax; //融资租赁项购置税

     private BigDecimal finLeaseVehiclevesselTax; //融资租赁项车船税

     private BigDecimal finLeaseGps; //融资租赁项GPS

     private BigDecimal finLeaseAccountinsurance; //融资租赁项责信保

     private BigDecimal finLeaseAddcostinsurance; //融资租赁项加装费用

     private BigDecimal finLeaseAftserCharge; //融资租赁项后服务费用

     private BigDecimal accManageExpense; //账户管理费

     private BigDecimal outputTax; //总销项税

     private BigDecimal vehicleIncome; //车价进项

     private BigDecimal downPaymentOutput; //首付销项

     private BigDecimal purchasingtaxTax; //购置税税额

     private BigDecimal businsuranceTax; //商业险税额

     private BigDecimal spinsurTax; //交强险税额

     private BigDecimal finLeaseGpstax; //融资项GPS税额

     private BigDecimal vrhicleInvoiceNotax; //车款发票金额(不含税)

     private BigDecimal businsuranceInvamoNotax; //融资租赁项商业险发票金额(不含税)

     private BigDecimal finLeaseSpinsurInvoice; //融资租赁项交强险发票金额(不含税)

     private BigDecimal purchasingtaxInvamoNotax; //购置税发票金额(不含税)

     private BigDecimal vehiclevesseltaxInvoice; //车船税发票金额

     private BigDecimal accountinsuranceInvoiceNotax; //责信保发票金额(不含税)

     private BigDecimal accManageExpenseInvoice; //账户管理费金额

     private BigDecimal vrhicleInvoiceTax; //车款发票税额

     private BigDecimal businsuranceInvoiceTax; //商业险发票税额

     private BigDecimal spinsurInvoiceTax; //交强险发票税额

     private BigDecimal purchasingtaxInvoiceTax; //购置税发票税额

     private BigDecimal accountinsuranceInvoiceTax; //责信保发票税额

     private BigDecimal longtermRecePrincipal; //长期应收款-本金

     private BigDecimal principalOutput; //本金销项

     private BigDecimal longtermReceInterest; //长期应收款-利息

     private BigDecimal customerRate; //客户利率(%)

     private BigDecimal clearingRate; //结算利率(%)

     private BigDecimal downPaymentAmount; //首付金额

     private BigDecimal finalPaymentAmount; //尾付金额

     private BigDecimal serviceChargeCustomer; //客户承担手续费（融资额*手续费率）

     private BigDecimal marginAmount; //保证金金额

     private BigDecimal perperiodCustomerRent; //每期客户租金

     private BigDecimal robberySecurityAmount; //无忧盗抢险金额

     private BigDecimal discountAmount; //贴息金额

     private BigDecimal gpsBasicPrice; //gps基础价

     private BigDecimal gpsRaisePrice; //gps加价

     private BigDecimal gpsServiceCharge; //gps服务费

     private BigDecimal extendedWarrantyAmount; //延保费用

     private BigDecimal loanAmount; //应放款额

     private BigDecimal residualPrincipal; //剩余本金

     @Length(max = 200)
     private String marginMatch; //保证金是否冲抵

     private BigDecimal manufacturerDiscountAmount; //厂家贴息金额

     private BigDecimal agencyDiscountAmount; //代理商贴息金额

     @Length(max = 200)
     private String detuManufDiscountAmount; //是否扣除厂家贴息后放款

     @Length(max = 200)
     private String detuAgencyDiscountAmount; //是否扣除代理商贴息后放款

     @Length(max = 200)
     private String whetherDiscount; //是否贴息

     private BigDecimal extraServiceCharge; //额外贴手续费金额

     private BigDecimal actualServiceCharge; //实际贴手续费金额

     private BigDecimal extraDiscountAmount; //额外贴息金额

     private BigDecimal actualDiscountAmount; //实际贴息金额

     @Length(max = 200)
     private String belongcomValue; //所属公司

     private Date contractStartDate; //合同生效日期

     private Date contractEndDate; //合同结束日期


     public void setContractValidatedId(Long contractValidatedId){
         this.contractValidatedId = contractValidatedId;
     }

     public Long getContractValidatedId(){
         return contractValidatedId;
     }

     public void setAccountingStatus(String accountingStatus){
         this.accountingStatus = accountingStatus;
     }

     public String getAccountingStatus(){
         return accountingStatus;
     }

     public void setAccountingDate(Date accountingDate){
         this.accountingDate = accountingDate;
     }

     public Date getAccountingDate(){
         return accountingDate;
     }

     public void setAccountingRemark(String accountingRemark){
         this.accountingRemark = accountingRemark;
     }

     public String getAccountingRemark(){
         return accountingRemark;
     }

     public void setBatchNum(String batchNum){
         this.batchNum = batchNum;
     }

     public String getBatchNum(){
         return batchNum;
     }

     public void setSourceSystem(String sourceSystem){
         this.sourceSystem = sourceSystem;
     }

     public String getSourceSystem(){
         return sourceSystem;
     }

     public void setUniqueCode(String uniqueCode){
         this.uniqueCode = uniqueCode;
     }

     public String getUniqueCode(){
         return uniqueCode;
     }

     public void setInvoiceEntityValue(String invoiceEntityValue){
         this.invoiceEntityValue = invoiceEntityValue;
     }

     public String getInvoiceEntityValue(){
         return invoiceEntityValue;
     }

     public void setSubcomValue(String subcomValue){
         this.subcomValue = subcomValue;
     }

     public String getSubcomValue(){
         return subcomValue;
     }

     public void setApplyNum(String applyNum){
         this.applyNum = applyNum;
     }

     public String getApplyNum(){
         return applyNum;
     }

     public void setContractNum(String contractNum){
         this.contractNum = contractNum;
     }

     public String getContractNum(){
         return contractNum;
     }

     public void setApplyType(String applyType){
         this.applyType = applyType;
     }

     public String getApplyType(){
         return applyType;
     }

     public void setCustomerName(String customerName){
         this.customerName = customerName;
     }

     public String getCustomerName(){
         return customerName;
     }

     public void setSourceVehicle(String sourceVehicle){
         this.sourceVehicle = sourceVehicle;
     }

     public String getSourceVehicle(){
         return sourceVehicle;
     }

     public void setSourceVehicleType(String sourceVehicleType){
         this.sourceVehicleType = sourceVehicleType;
     }

     public String getSourceVehicleType(){
         return sourceVehicleType;
     }

     public void setLeasingType(String leasingType){
         this.leasingType = leasingType;
     }

     public String getLeasingType(){
         return leasingType;
     }

     public void setApplyStatus(String applyStatus){
         this.applyStatus = applyStatus;
     }

     public String getApplyStatus(){
         return applyStatus;
     }

     public void setContractStatus(String contractStatus){
         this.contractStatus = contractStatus;
     }

     public String getContractStatus(){
         return contractStatus;
     }

     public void setVehiclePrice(BigDecimal vehiclePrice){
         this.vehiclePrice = vehiclePrice;
     }

     public BigDecimal getVehiclePrice(){
         return vehiclePrice;
     }

     public void setVrhicleIdentifyNum(String vrhicleIdentifyNum){
         this.vrhicleIdentifyNum = vrhicleIdentifyNum;
     }

     public String getVrhicleIdentifyNum(){
         return vrhicleIdentifyNum;
     }

     public void setBrandAmount(BigDecimal brandAmount){
         this.brandAmount = brandAmount;
     }

     public BigDecimal getBrandAmount(){
         return brandAmount;
     }

     public void setPurchasingtaxInvoiceAmount(BigDecimal purchasingtaxInvoiceAmount){
         this.purchasingtaxInvoiceAmount = purchasingtaxInvoiceAmount;
     }

     public BigDecimal getPurchasingtaxInvoiceAmount(){
         return purchasingtaxInvoiceAmount;
     }

     public void setPreRentAmount(BigDecimal preRentAmount){
         this.preRentAmount = preRentAmount;
     }

     public BigDecimal getPreRentAmount(){
         return preRentAmount;
     }

     public void setInvestAmount(BigDecimal investAmount){
         this.investAmount = investAmount;
     }

     public BigDecimal getInvestAmount(){
         return investAmount;
     }

     public void setFinAmount(BigDecimal finAmount){
         this.finAmount = finAmount;
     }

     public BigDecimal getFinAmount(){
         return finAmount;
     }

     public void setFinLeaseVrhicle(BigDecimal finLeaseVrhicle){
         this.finLeaseVrhicle = finLeaseVrhicle;
     }

     public BigDecimal getFinLeaseVrhicle(){
         return finLeaseVrhicle;
     }

     public void setFinLeaseBusinsurance(BigDecimal finLeaseBusinsurance){
         this.finLeaseBusinsurance = finLeaseBusinsurance;
     }

     public BigDecimal getFinLeaseBusinsurance(){
         return finLeaseBusinsurance;
     }

     public void setFinLeaseSpinsurance(BigDecimal finLeaseSpinsurance){
         this.finLeaseSpinsurance = finLeaseSpinsurance;
     }

     public BigDecimal getFinLeaseSpinsurance(){
         return finLeaseSpinsurance;
     }

     public void setFinLeasePurchasingtax(BigDecimal finLeasePurchasingtax){
         this.finLeasePurchasingtax = finLeasePurchasingtax;
     }

     public BigDecimal getFinLeasePurchasingtax(){
         return finLeasePurchasingtax;
     }

     public void setFinLeaseVehiclevesselTax(BigDecimal finLeaseVehiclevesselTax){
         this.finLeaseVehiclevesselTax = finLeaseVehiclevesselTax;
     }

     public BigDecimal getFinLeaseVehiclevesselTax(){
         return finLeaseVehiclevesselTax;
     }

     public void setFinLeaseGps(BigDecimal finLeaseGps){
         this.finLeaseGps = finLeaseGps;
     }

     public BigDecimal getFinLeaseGps(){
         return finLeaseGps;
     }

     public void setFinLeaseAccountinsurance(BigDecimal finLeaseAccountinsurance){
         this.finLeaseAccountinsurance = finLeaseAccountinsurance;
     }

     public BigDecimal getFinLeaseAccountinsurance(){
         return finLeaseAccountinsurance;
     }

     public void setFinLeaseAddcostinsurance(BigDecimal finLeaseAddcostinsurance){
         this.finLeaseAddcostinsurance = finLeaseAddcostinsurance;
     }

     public BigDecimal getFinLeaseAddcostinsurance(){
         return finLeaseAddcostinsurance;
     }

     public void setFinLeaseAftserCharge(BigDecimal finLeaseAftserCharge){
         this.finLeaseAftserCharge = finLeaseAftserCharge;
     }

     public BigDecimal getFinLeaseAftserCharge(){
         return finLeaseAftserCharge;
     }

     public void setAccManageExpense(BigDecimal accManageExpense){
         this.accManageExpense = accManageExpense;
     }

     public BigDecimal getAccManageExpense(){
         return accManageExpense;
     }

     public void setOutputTax(BigDecimal outputTax){
         this.outputTax = outputTax;
     }

     public BigDecimal getOutputTax(){
         return outputTax;
     }

     public void setVehicleIncome(BigDecimal vehicleIncome){
         this.vehicleIncome = vehicleIncome;
     }

     public BigDecimal getVehicleIncome(){
         return vehicleIncome;
     }

     public void setDownPaymentOutput(BigDecimal downPaymentOutput){
         this.downPaymentOutput = downPaymentOutput;
     }

     public BigDecimal getDownPaymentOutput(){
         return downPaymentOutput;
     }

     public void setPurchasingtaxTax(BigDecimal purchasingtaxTax){
         this.purchasingtaxTax = purchasingtaxTax;
     }

     public BigDecimal getPurchasingtaxTax(){
         return purchasingtaxTax;
     }

     public void setBusinsuranceTax(BigDecimal businsuranceTax){
         this.businsuranceTax = businsuranceTax;
     }

     public BigDecimal getBusinsuranceTax(){
         return businsuranceTax;
     }

     public void setSpinsurTax(BigDecimal spinsurTax){
         this.spinsurTax = spinsurTax;
     }

     public BigDecimal getSpinsurTax(){
         return spinsurTax;
     }

     public void setFinLeaseGpstax(BigDecimal finLeaseGpstax){
         this.finLeaseGpstax = finLeaseGpstax;
     }

     public BigDecimal getFinLeaseGpstax(){
         return finLeaseGpstax;
     }

     public void setVrhicleInvoiceNotax(BigDecimal vrhicleInvoiceNotax){
         this.vrhicleInvoiceNotax = vrhicleInvoiceNotax;
     }

     public BigDecimal getVrhicleInvoiceNotax(){
         return vrhicleInvoiceNotax;
     }

     public void setBusinsuranceInvamoNotax(BigDecimal businsuranceInvamoNotax){
         this.businsuranceInvamoNotax = businsuranceInvamoNotax;
     }

     public BigDecimal getBusinsuranceInvamoNotax(){
         return businsuranceInvamoNotax;
     }

     public void setFinLeaseSpinsurInvoice(BigDecimal finLeaseSpinsurInvoice){
         this.finLeaseSpinsurInvoice = finLeaseSpinsurInvoice;
     }

     public BigDecimal getFinLeaseSpinsurInvoice(){
         return finLeaseSpinsurInvoice;
     }

     public void setPurchasingtaxInvamoNotax(BigDecimal purchasingtaxInvamoNotax){
         this.purchasingtaxInvamoNotax = purchasingtaxInvamoNotax;
     }

     public BigDecimal getPurchasingtaxInvamoNotax(){
         return purchasingtaxInvamoNotax;
     }

     public void setVehiclevesseltaxInvoice(BigDecimal vehiclevesseltaxInvoice){
         this.vehiclevesseltaxInvoice = vehiclevesseltaxInvoice;
     }

     public BigDecimal getVehiclevesseltaxInvoice(){
         return vehiclevesseltaxInvoice;
     }

     public void setAccountinsuranceInvoiceNotax(BigDecimal accountinsuranceInvoiceNotax){
         this.accountinsuranceInvoiceNotax = accountinsuranceInvoiceNotax;
     }

     public BigDecimal getAccountinsuranceInvoiceNotax(){
         return accountinsuranceInvoiceNotax;
     }

     public void setAccManageExpenseInvoice(BigDecimal accManageExpenseInvoice){
         this.accManageExpenseInvoice = accManageExpenseInvoice;
     }

     public BigDecimal getAccManageExpenseInvoice(){
         return accManageExpenseInvoice;
     }

     public void setVrhicleInvoiceTax(BigDecimal vrhicleInvoiceTax){
         this.vrhicleInvoiceTax = vrhicleInvoiceTax;
     }

     public BigDecimal getVrhicleInvoiceTax(){
         return vrhicleInvoiceTax;
     }

     public void setBusinsuranceInvoiceTax(BigDecimal businsuranceInvoiceTax){
         this.businsuranceInvoiceTax = businsuranceInvoiceTax;
     }

     public BigDecimal getBusinsuranceInvoiceTax(){
         return businsuranceInvoiceTax;
     }

     public void setSpinsurInvoiceTax(BigDecimal spinsurInvoiceTax){
         this.spinsurInvoiceTax = spinsurInvoiceTax;
     }

     public BigDecimal getSpinsurInvoiceTax(){
         return spinsurInvoiceTax;
     }

     public void setPurchasingtaxInvoiceTax(BigDecimal purchasingtaxInvoiceTax){
         this.purchasingtaxInvoiceTax = purchasingtaxInvoiceTax;
     }

     public BigDecimal getPurchasingtaxInvoiceTax(){
         return purchasingtaxInvoiceTax;
     }

     public void setAccountinsuranceInvoiceTax(BigDecimal accountinsuranceInvoiceTax){
         this.accountinsuranceInvoiceTax = accountinsuranceInvoiceTax;
     }

     public BigDecimal getAccountinsuranceInvoiceTax(){
         return accountinsuranceInvoiceTax;
     }

     public void setBigDecimaltermRecePrincipal(BigDecimal longtermRecePrincipal){
         this.longtermRecePrincipal = longtermRecePrincipal;
     }

     public BigDecimal getBigDecimaltermRecePrincipal(){
         return longtermRecePrincipal;
     }

     public void setPrincipalOutput(BigDecimal principalOutput){
         this.principalOutput = principalOutput;
     }

     public BigDecimal getPrincipalOutput(){
         return principalOutput;
     }

     public void setBigDecimaltermReceInterest(BigDecimal longtermReceInterest){
         this.longtermReceInterest = longtermReceInterest;
     }

     public BigDecimal getBigDecimaltermReceInterest(){
         return longtermReceInterest;
     }

     public void setCustomerRate(BigDecimal customerRate){
         this.customerRate = customerRate;
     }

     public BigDecimal getCustomerRate(){
         return customerRate;
     }

     public void setClearingRate(BigDecimal clearingRate){
         this.clearingRate = clearingRate;
     }

     public BigDecimal getClearingRate(){
         return clearingRate;
     }

     public void setDownPaymentAmount(BigDecimal downPaymentAmount){
         this.downPaymentAmount = downPaymentAmount;
     }

     public BigDecimal getDownPaymentAmount(){
         return downPaymentAmount;
     }

     public void setFinalPaymentAmount(BigDecimal finalPaymentAmount){
         this.finalPaymentAmount = finalPaymentAmount;
     }

     public BigDecimal getFinalPaymentAmount(){
         return finalPaymentAmount;
     }

     public void setServiceChargeCustomer(BigDecimal serviceChargeCustomer){
         this.serviceChargeCustomer = serviceChargeCustomer;
     }

     public BigDecimal getServiceChargeCustomer(){
         return serviceChargeCustomer;
     }

     public void setMarginAmount(BigDecimal marginAmount){
         this.marginAmount = marginAmount;
     }

     public BigDecimal getMarginAmount(){
         return marginAmount;
     }

     public void setPerperiodCustomerRent(BigDecimal perperiodCustomerRent){
         this.perperiodCustomerRent = perperiodCustomerRent;
     }

     public BigDecimal getPerperiodCustomerRent(){
         return perperiodCustomerRent;
     }

     public void setRobberySecurityAmount(BigDecimal robberySecurityAmount){
         this.robberySecurityAmount = robberySecurityAmount;
     }

     public BigDecimal getRobberySecurityAmount(){
         return robberySecurityAmount;
     }

     public void setDiscountAmount(BigDecimal discountAmount){
         this.discountAmount = discountAmount;
     }

     public BigDecimal getDiscountAmount(){
         return discountAmount;
     }

     public void setGpsBasicPrice(BigDecimal gpsBasicPrice){
         this.gpsBasicPrice = gpsBasicPrice;
     }

     public BigDecimal getGpsBasicPrice(){
         return gpsBasicPrice;
     }

     public void setGpsRaisePrice(BigDecimal gpsRaisePrice){
         this.gpsRaisePrice = gpsRaisePrice;
     }

     public BigDecimal getGpsRaisePrice(){
         return gpsRaisePrice;
     }

     public void setGpsServiceCharge(BigDecimal gpsServiceCharge){
         this.gpsServiceCharge = gpsServiceCharge;
     }

     public BigDecimal getGpsServiceCharge(){
         return gpsServiceCharge;
     }

     public void setExtendedWarrantyAmount(BigDecimal extendedWarrantyAmount){
         this.extendedWarrantyAmount = extendedWarrantyAmount;
     }

     public BigDecimal getExtendedWarrantyAmount(){
         return extendedWarrantyAmount;
     }

     public void setLoanAmount(BigDecimal loanAmount){
         this.loanAmount = loanAmount;
     }

     public BigDecimal getLoanAmount(){
         return loanAmount;
     }

     public void setResidualPrincipal(BigDecimal residualPrincipal){
         this.residualPrincipal = residualPrincipal;
     }

     public BigDecimal getResidualPrincipal(){
         return residualPrincipal;
     }

     public void setMarginMatch(String marginMatch){
         this.marginMatch = marginMatch;
     }

     public String getMarginMatch(){
         return marginMatch;
     }

     public void setManufacturerDiscountAmount(BigDecimal manufacturerDiscountAmount){
         this.manufacturerDiscountAmount = manufacturerDiscountAmount;
     }

     public BigDecimal getManufacturerDiscountAmount(){
         return manufacturerDiscountAmount;
     }

     public void setAgencyDiscountAmount(BigDecimal agencyDiscountAmount){
         this.agencyDiscountAmount = agencyDiscountAmount;
     }

     public BigDecimal getAgencyDiscountAmount(){
         return agencyDiscountAmount;
     }

     public void setDetuManufDiscountAmount(String detuManufDiscountAmount){
         this.detuManufDiscountAmount = detuManufDiscountAmount;
     }

     public String getDetuManufDiscountAmount(){
         return detuManufDiscountAmount;
     }

     public void setDetuAgencyDiscountAmount(String detuAgencyDiscountAmount){
         this.detuAgencyDiscountAmount = detuAgencyDiscountAmount;
     }

     public String getDetuAgencyDiscountAmount(){
         return detuAgencyDiscountAmount;
     }

     public void setWhetherDiscount(String whetherDiscount){
         this.whetherDiscount = whetherDiscount;
     }

     public String getWhetherDiscount(){
         return whetherDiscount;
     }

     public void setExtraServiceCharge(BigDecimal extraServiceCharge){
         this.extraServiceCharge = extraServiceCharge;
     }

     public BigDecimal getExtraServiceCharge(){
         return extraServiceCharge;
     }

     public void setActualServiceCharge(BigDecimal actualServiceCharge){
         this.actualServiceCharge = actualServiceCharge;
     }

     public BigDecimal getActualServiceCharge(){
         return actualServiceCharge;
     }

     public void setExtraDiscountAmount(BigDecimal extraDiscountAmount){
         this.extraDiscountAmount = extraDiscountAmount;
     }

     public BigDecimal getExtraDiscountAmount(){
         return extraDiscountAmount;
     }

     public void setActualDiscountAmount(BigDecimal actualDiscountAmount){
         this.actualDiscountAmount = actualDiscountAmount;
     }

     public BigDecimal getActualDiscountAmount(){
         return actualDiscountAmount;
     }

     public void setBelongcomValue(String belongcomValue){
         this.belongcomValue = belongcomValue;
     }

     public String getBelongcomValue(){
         return belongcomValue;
     }

     public void setContractStartDate(Date contractStartDate){
         this.contractStartDate = contractStartDate;
     }

     public Date getContractStartDate(){
         return contractStartDate;
     }

     public void setContractEndDate(Date contractEndDate){
         this.contractEndDate = contractEndDate;
     }

     public Date getContractEndDate(){
         return contractEndDate;
     }

     }
