package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_itf_mal_clear_interface")
public class ItfMalClearInterface extends BaseDTO {

     public static final String FIELD_OPL_CONTRACT_ID = "oplContractId";
     public static final String FIELD_ACCOUNTING_STATUS = "accountingStatus";
     public static final String FIELD_ACCOUNTING_DATE = "accountingDate";
     public static final String FIELD_ACCOUNTING_REMARK = "accountingRemark";
     public static final String FIELD_UNIQUE_CODE = "uniqueCode";
     public static final String FIELD_APPLY_NUM = "applyNum";
     public static final String FIELD_RCPT_AMOUNT = "rcptAmount";
     public static final String FIELD_CURRENCY = "currency";
     public static final String FIELD_RCPT_DATE = "rcptDate";
     public static final String FIELD_RCPT_TYPE = "rcptType";
     public static final String FIELD_SERIAL_NUM = "serialNum";
     public static final String FIELD_RCPT_ACC_NAME = "rcptAccName";
     public static final String FIELD_RCPT_COM = "rcptCom";
     public static final String FIELD_RCPT_INTERCOM = "rcptIntercom";
     public static final String FIELD_ODD_CORPUS = "oddCorpus";
     public static final String FIELD_SERVICE_CHARGE = "serviceCharge";
     public static final String FIELD_DEDIT = "dedit";
     public static final String FIELD_MOUNTH_INTEREST = "mounthInterest";
     public static final String FIELD_NOT_PAID_INSURANCE = "notPaidInsurance";
     public static final String FIELD_NOT_PAID_VEHICLEVESSEL_TAX = "notPaidVehiclevesselTax";
     public static final String FIELD_NOT_PAID_GPS = "notPaidGps";
     public static final String FIELD_CANCELLATION_AMOUNT = "cancellationAmount";
     public static final String FIELD_MARGIN_DEDUCTION_AMOUNT = "marginDeductionAmount";
     public static final String FIELD_VEHICLE_DISPOSAL_AMOUNT = "vehicleDisposalAmount";
     public static final String FIELD_BATCH_NUM = "batchNum";


     @Id
     @GeneratedValue
     private Long oplContractId; //表ID，主键，供其他表做外键

     @Length(max = 30)
     private String accountingStatus; //入账状态

     private Date accountingDate; //入账日期

     @Length(max = 255)
     private String accountingRemark; //入账消息（如凭证编号等，可以考虑是否需要多个）

     @Length(max = 255)
     private String uniqueCode; //唯一标识

     @Length(max = 255)
     private String applyNum; //申请号

     private BigDecimal rcptAmount; //核销/撤销核销金额

     @Length(max = 255)
     private String currency; //币种

     @Length(max = 255)
     private String rcptDate; //核销/撤销核销日期

     @Length(max = 255)
     private String rcptType; //收款类型

     @Length(max = 255)
     private String serialNum; //银行流水编号/佣金编号

     @Length(max = 255)
     private String rcptAccName; //收款账户名称

     @Length(max = 255)
     private String rcptCom; //收款方公司段

     @Length(max = 255)
     private String rcptIntercom; //收款方关联方段

     private BigDecimal oddCorpus; //剩余本金

     private BigDecimal serviceCharge; //手续费

     private BigDecimal dedit; //违约金

     private BigDecimal mounthInterest; //当月利息

     private BigDecimal notPaidInsurance; //未付保费

     private BigDecimal notPaidVehiclevesselTax; //未付车船税

     private BigDecimal notPaidGps; //未付GPS费

     private BigDecimal cancellationAmount; //费用免除金额

     private BigDecimal marginDeductionAmount; //保证金抵扣金额

     private BigDecimal vehicleDisposalAmount; //车辆处置金额

     @Length(max = 255)
     private String batchNum; //批次号


     public void setOplContractId(Long oplContractId){
         this.oplContractId = oplContractId;
     }

     public Long getOplContractId(){
         return oplContractId;
     }

     public void setAccountingStatus(String accountingStatus){
         this.accountingStatus = accountingStatus;
     }

     public String getAccountingStatus(){
         return accountingStatus;
     }

     public void setAccountingDate(Date accountingDate){
         this.accountingDate = accountingDate;
     }

     public Date getAccountingDate(){
         return accountingDate;
     }

     public void setAccountingRemark(String accountingRemark){
         this.accountingRemark = accountingRemark;
     }

     public String getAccountingRemark(){
         return accountingRemark;
     }

     public void setUniqueCode(String uniqueCode){
         this.uniqueCode = uniqueCode;
     }

     public String getUniqueCode(){
         return uniqueCode;
     }

     public void setApplyNum(String applyNum){
         this.applyNum = applyNum;
     }

     public String getApplyNum(){
         return applyNum;
     }

     public void setRcptAmount(BigDecimal rcptAmount){
         this.rcptAmount = rcptAmount;
     }

     public BigDecimal getRcptAmount(){
         return rcptAmount;
     }

     public void setCurrency(String currency){
         this.currency = currency;
     }

     public String getCurrency(){
         return currency;
     }

     public void setRcptDate(String rcptDate){
         this.rcptDate = rcptDate;
     }

     public String getRcptDate(){
         return rcptDate;
     }

     public void setRcptType(String rcptType){
         this.rcptType = rcptType;
     }

     public String getRcptType(){
         return rcptType;
     }

     public void setSerialNum(String serialNum){
         this.serialNum = serialNum;
     }

     public String getSerialNum(){
         return serialNum;
     }

     public void setRcptAccName(String rcptAccName){
         this.rcptAccName = rcptAccName;
     }

     public String getRcptAccName(){
         return rcptAccName;
     }

     public void setRcptCom(String rcptCom){
         this.rcptCom = rcptCom;
     }

     public String getRcptCom(){
         return rcptCom;
     }

     public void setRcptIntercom(String rcptIntercom){
         this.rcptIntercom = rcptIntercom;
     }

     public String getRcptIntercom(){
         return rcptIntercom;
     }

     public void setOddCorpus(BigDecimal oddCorpus){
         this.oddCorpus = oddCorpus;
     }

     public BigDecimal getOddCorpus(){
         return oddCorpus;
     }

     public void setServiceCharge(BigDecimal serviceCharge){
         this.serviceCharge = serviceCharge;
     }

     public BigDecimal getServiceCharge(){
         return serviceCharge;
     }

     public void setDedit(BigDecimal dedit){
         this.dedit = dedit;
     }

     public BigDecimal getDedit(){
         return dedit;
     }

     public void setMounthInterest(BigDecimal mounthInterest){
         this.mounthInterest = mounthInterest;
     }

     public BigDecimal getMounthInterest(){
         return mounthInterest;
     }

     public void setNotPaidInsurance(BigDecimal notPaidInsurance){
         this.notPaidInsurance = notPaidInsurance;
     }

     public BigDecimal getNotPaidInsurance(){
         return notPaidInsurance;
     }

     public void setNotPaidVehiclevesselTax(BigDecimal notPaidVehiclevesselTax){
         this.notPaidVehiclevesselTax = notPaidVehiclevesselTax;
     }

     public BigDecimal getNotPaidVehiclevesselTax(){
         return notPaidVehiclevesselTax;
     }

     public void setNotPaidGps(BigDecimal notPaidGps){
         this.notPaidGps = notPaidGps;
     }

     public BigDecimal getNotPaidGps(){
         return notPaidGps;
     }

     public void setCancellationAmount(BigDecimal cancellationAmount){
         this.cancellationAmount = cancellationAmount;
     }

     public BigDecimal getCancellationAmount(){
         return cancellationAmount;
     }

     public void setMarginDeductionAmount(BigDecimal marginDeductionAmount){
         this.marginDeductionAmount = marginDeductionAmount;
     }

     public BigDecimal getMarginDeductionAmount(){
         return marginDeductionAmount;
     }

     public void setVehicleDisposalAmount(BigDecimal vehicleDisposalAmount){
         this.vehicleDisposalAmount = vehicleDisposalAmount;
     }

     public BigDecimal getVehicleDisposalAmount(){
         return vehicleDisposalAmount;
     }

     public void setBatchNum(String batchNum){
         this.batchNum = batchNum;
     }

     public String getBatchNum(){
         return batchNum;
     }

     }
