package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_itf_pan_apply")
public class ItfPanApply extends BaseDTO {

     public static final String FIELD_PAN_PRI_ID = "panPriId";
     public static final String FIELD_ACCOUNTING_STATUS = "accountingStatus";
     public static final String FIELD_ACCOUNTING_DATE = "accountingDate";
     public static final String FIELD_ACCOUNTING_REMARK = "accountingRemark";
     public static final String FIELD_UNIQUE_CODE = "uniqueCode";
     public static final String FIELD_APPLY_NUM = "applyNum";
     public static final String FIELD_APPLY_AMOUNT = "applyAmount";
     public static final String FIELD_CURRENCY = "currency";
     public static final String FIELD_APPLY_DATE = "applyDate";
     public static final String FIELD_RCPT_TYPE = "rcptType";
     public static final String FIELD_RCPT_NUM = "rcptNum";
     public static final String FIELD_RCPT_PARTY = "rcptParty";
     public static final String FIELD_RECPT_COM = "recptCom";
     public static final String FIELD_RECPT_INTERCOM = "recptIntercom";
     public static final String FIELD_BATCH_NUM = "batchNum";


     @Id
     @GeneratedValue
     private Long panPriId; //表ID，主键，供其他表做外键

     @Length(max = 200)
     private String accountingStatus; //过账状态

     private Date accountingDate; //过账日期

     @Length(max = 255)
     private String accountingRemark; //过账标志

     @Length(max = 200)
     private String uniqueCode; //唯一标识

     @Length(max = 200)
     private String applyNum; //申请号

     private BigDecimal applyAmount; //核销/撤销核销金额

     @Length(max = 200)
     private String currency; //币种

     private Date applyDate; //核销/撤销核销日期

     @Length(max = 200)
     private String rcptType; //收款类型

     @Length(max = 200)
     private String rcptNum; //收款编号

     @Length(max = 200)
     private String rcptParty; //收款方

     @Length(max = 200)
     private String recptCom; //收款方公司段

     @Length(max = 200)
     private String recptIntercom; //收款方关联方段

     @Length(max = 200)
     private String batchNum; //批次号


     public void setPanPriId(Long panPriId){
         this.panPriId = panPriId;
     }

     public Long getPanPriId(){
         return panPriId;
     }

     public void setAccountingStatus(String accountingStatus){
         this.accountingStatus = accountingStatus;
     }

     public String getAccountingStatus(){
         return accountingStatus;
     }

     public void setAccountingDate(Date accountingDate){
         this.accountingDate = accountingDate;
     }

     public Date getAccountingDate(){
         return accountingDate;
     }

     public void setAccountingRemark(String accountingRemark){
         this.accountingRemark = accountingRemark;
     }

     public String getAccountingRemark(){
         return accountingRemark;
     }

     public void setUniqueCode(String uniqueCode){
         this.uniqueCode = uniqueCode;
     }

     public String getUniqueCode(){
         return uniqueCode;
     }

     public void setApplyNum(String applyNum){
         this.applyNum = applyNum;
     }

     public String getApplyNum(){
         return applyNum;
     }

     public void setApplyAmount(BigDecimal applyAmount){
         this.applyAmount = applyAmount;
     }

     public BigDecimal getApplyAmount(){
         return applyAmount;
     }

     public void setCurrency(String currency){
         this.currency = currency;
     }

     public String getCurrency(){
         return currency;
     }

     public void setApplyDate(Date applyDate){
         this.applyDate = applyDate;
     }

     public Date getApplyDate(){
         return applyDate;
     }

     public void setRcptType(String rcptType){
         this.rcptType = rcptType;
     }

     public String getRcptType(){
         return rcptType;
     }

     public void setRcptNum(String rcptNum){
         this.rcptNum = rcptNum;
     }

     public String getRcptNum(){
         return rcptNum;
     }

     public void setRcptParty(String rcptParty){
         this.rcptParty = rcptParty;
     }

     public String getRcptParty(){
         return rcptParty;
     }

     public void setRecptCom(String recptCom){
         this.recptCom = recptCom;
     }

     public String getRecptCom(){
         return recptCom;
     }

     public void setRecptIntercom(String recptIntercom){
         this.recptIntercom = recptIntercom;
     }

     public String getRecptIntercom(){
         return recptIntercom;
     }

     public void setBatchNum(String batchNum){
         this.batchNum = batchNum;
     }

     public String getBatchNum(){
         return batchNum;
     }

     }
