package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_itf_psm_inv")
public class ItfPsmInv extends BaseDTO {

     public static final String FIELD_PSM_INV_ID = "psmInvId";
     public static final String FIELD_ACCOUNTING_STATUS = "accountingStatus";
     public static final String FIELD_ACCOUNTING_DATE = "accountingDate";
     public static final String FIELD_ACCOUNTING_REMARK = "accountingRemark";
     public static final String FIELD_BATCH_NUM = "batchNum";
     public static final String FIELD_SOURCE_SYSTEM = "sourceSystem";
     public static final String FIELD_UNIQUE_CODE = "uniqueCode";
     public static final String FIELD_INV_TYPE = "invType";
     public static final String FIELD_INV_ENT = "invEnt";
     public static final String FIELD_INV_NUM = "invNum";
     public static final String FIELD_VENDOR = "vendor";
     public static final String FIELD_INV_DATE = "invDate";
     public static final String FIELD_INV_CURRENCY = "invCurrency";
     public static final String FIELD_CAR_NUM = "carNum";
     public static final String FIELD_CAR_INV_AMOUT = "carInvAmout";
     public static final String FIELD_CAR_TAX_AMOUT = "carTaxAmout";
     public static final String FIELD_ENT_CODE = "entCode";
     public static final String FIELD_GROUP_CODE = "groupCode";


     @Id
     @GeneratedValue
     private Long psmInvId; //表ID，主键，供其他表做外键

     @Length(max = 30)
     private String accountingStatus; //入账状态

     private Date accountingDate; //入账日期

     @Length(max = 200)
     private String accountingRemark; //入账消息（如凭证编号等，可以考虑是否需要多个）

     @Length(max = 200)
     private String batchNum; //批次号

     @Length(max = 200)
     private String sourceSystem; //来源系统

     @Length(max = 200)
     private String uniqueCode; //唯一标识

     @Length(max = 200)
     private String invType; //发票类型

     @Length(max = 200)
     private String invEnt; //发票主体

     @Length(max = 200)
     private String invNum; //发票号码

     @Length(max = 200)
     private String vendor; //供应商

     private Date invDate; //发票日期

     @Length(max = 200)
     private String invCurrency; //发票币种

     @Length(max = 200)
     private String carNum; //车架号

     private BigDecimal carInvAmout; //车辆发票金额

     private BigDecimal carTaxAmout; //车辆发票税额

     @Length(max = 200)
     private String entCode; //主体编码

     @Length(max = 200)
     private String groupCode; //所属集团


     public void setPsmInvId(Long psmInvId){
         this.psmInvId = psmInvId;
     }

     public Long getPsmInvId(){
         return psmInvId;
     }

     public void setAccountingStatus(String accountingStatus){
         this.accountingStatus = accountingStatus;
     }

     public String getAccountingStatus(){
         return accountingStatus;
     }

     public void setAccountingDate(Date accountingDate){
         this.accountingDate = accountingDate;
     }

     public Date getAccountingDate(){
         return accountingDate;
     }

     public void setAccountingRemark(String accountingRemark){
         this.accountingRemark = accountingRemark;
     }

     public String getAccountingRemark(){
         return accountingRemark;
     }

     public void setBatchNum(String batchNum){
         this.batchNum = batchNum;
     }

     public String getBatchNum(){
         return batchNum;
     }

     public void setSourceSystem(String sourceSystem){
         this.sourceSystem = sourceSystem;
     }

     public String getSourceSystem(){
         return sourceSystem;
     }

     public void setUniqueCode(String uniqueCode){
         this.uniqueCode = uniqueCode;
     }

     public String getUniqueCode(){
         return uniqueCode;
     }

     public void setInvType(String invType){
         this.invType = invType;
     }

     public String getInvType(){
         return invType;
     }

     public void setInvEnt(String invEnt){
         this.invEnt = invEnt;
     }

     public String getInvEnt(){
         return invEnt;
     }

     public void setInvNum(String invNum){
         this.invNum = invNum;
     }

     public String getInvNum(){
         return invNum;
     }

     public void setVendor(String vendor){
         this.vendor = vendor;
     }

     public String getVendor(){
         return vendor;
     }

     public void setInvDate(Date invDate){
         this.invDate = invDate;
     }

     public Date getInvDate(){
         return invDate;
     }

     public void setInvCurrency(String invCurrency){
         this.invCurrency = invCurrency;
     }

     public String getInvCurrency(){
         return invCurrency;
     }

     public void setCarNum(String carNum){
         this.carNum = carNum;
     }

     public String getCarNum(){
         return carNum;
     }

     public void setCarInvAmout(BigDecimal carInvAmout){
         this.carInvAmout = carInvAmout;
     }

     public BigDecimal getCarInvAmout(){
         return carInvAmout;
     }

     public void setCarTaxAmout(BigDecimal carTaxAmout){
         this.carTaxAmout = carTaxAmout;
     }

     public BigDecimal getCarTaxAmout(){
         return carTaxAmout;
     }

     public void setEntCode(String entCode){
         this.entCode = entCode;
     }

     public String getEntCode(){
         return entCode;
     }

     public void setGroupCode(String groupCode){
         this.groupCode = groupCode;
     }

     public String getGroupCode(){
         return groupCode;
     }

     }
