package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_itf_rcpt_line")
public class ItfRcptLine extends BaseDTO {

     public static final String FIELD_RCPT_PRI_ID = "rcptPriId";
     public static final String FIELD_ACCOUNTING_STATUS = "accountingStatus";
     public static final String FIELD_ACCOUNTING_DATE = "accountingDate";
     public static final String FIELD_ACCOUNTING_REMARK = "accountingRemark";
     public static final String FIELD_UNIQUE_CODE = "uniqueCode";
     public static final String FIELD_RCPT_DATE = "rcptDate";
     public static final String FIELD_RCPT_ACC_NAME = "rcptAccName";
     public static final String FIELD_RCPT_ACC_NUM = "rcptAccNum";
     public static final String FIELD_RECIPROCAL_ACC_NAME = "reciprocalAccName";
     public static final String FIELD_RECIPROCAL_ACC_NUM = "reciprocalAccNum";
     public static final String FIELD_RCPT_AMOUNT = "rcptAmount";
     public static final String FIELD_CURRENCY = "currency";
     public static final String FIELD_SERIAL_NUM = "serialNum";
     public static final String FIELD_DEDUCTION_METHOD = "deductionMethod";
     public static final String FIELD_DELETED = "deleted";
     public static final String FIELD_COM = "com";
     public static final String FIELD_SUBACC = "subacc";
     public static final String FIELD_LEDGER_NAME = "ledgerName";
     public static final String FIELD_BATCH_NUM = "batchNum";


     @Id
     @GeneratedValue
     private Long rcptPriId; //表ID，主键，供其他表做外键

     @Length(max = 200)
     private String accountingStatus; //过账状态

     private Date accountingDate; //过账日期

     @Length(max = 255)
     private String accountingRemark; //过账标志

     @Length(max = 200)
     private String uniqueCode; //唯一标识

     private Date rcptDate; //收款日期

     @Length(max = 200)
     private String rcptAccName; //收款账户名称

     @Length(max = 200)
     private String rcptAccNum; //收款账号

     @Length(max = 200)
     private String reciprocalAccName; //对方户名

     @Length(max = 200)
     private String reciprocalAccNum; //对方账号

     private BigDecimal rcptAmount; //收款金额

     @Length(max = 200)
     private String currency; //币种

     @Length(max = 200)
     private String serialNum; //银行流水编号

     @Length(max = 200)
     private String deductionMethod; //扣款渠道

     @Length(max = 200)
     private String deleted; //是否删除

     @Length(max = 200)
     private String com; //公司段

     @Length(max = 200)
     private String subacc; //明细段

     @Length(max = 200)
     private String ledgerName; //分类账名称

     @Length(max = 200)
     private String batchNum; //批次号


     public void setRcptPriId(Long rcptPriId){
         this.rcptPriId = rcptPriId;
     }

     public Long getRcptPriId(){
         return rcptPriId;
     }

     public void setAccountingStatus(String accountingStatus){
         this.accountingStatus = accountingStatus;
     }

     public String getAccountingStatus(){
         return accountingStatus;
     }

     public void setAccountingDate(Date accountingDate){
         this.accountingDate = accountingDate;
     }

     public Date getAccountingDate(){
         return accountingDate;
     }

     public void setAccountingRemark(String accountingRemark){
         this.accountingRemark = accountingRemark;
     }

     public String getAccountingRemark(){
         return accountingRemark;
     }

     public void setUniqueCode(String uniqueCode){
         this.uniqueCode = uniqueCode;
     }

     public String getUniqueCode(){
         return uniqueCode;
     }

     public void setRcptDate(Date rcptDate){
         this.rcptDate = rcptDate;
     }

     public Date getRcptDate(){
         return rcptDate;
     }

     public void setRcptAccName(String rcptAccName){
         this.rcptAccName = rcptAccName;
     }

     public String getRcptAccName(){
         return rcptAccName;
     }

     public void setRcptAccNum(String rcptAccNum){
         this.rcptAccNum = rcptAccNum;
     }

     public String getRcptAccNum(){
         return rcptAccNum;
     }

     public void setReciprocalAccName(String reciprocalAccName){
         this.reciprocalAccName = reciprocalAccName;
     }

     public String getReciprocalAccName(){
         return reciprocalAccName;
     }

     public void setReciprocalAccNum(String reciprocalAccNum){
         this.reciprocalAccNum = reciprocalAccNum;
     }

     public String getReciprocalAccNum(){
         return reciprocalAccNum;
     }

     public void setRcptAmount(BigDecimal rcptAmount){
         this.rcptAmount = rcptAmount;
     }

     public BigDecimal getRcptAmount(){
         return rcptAmount;
     }

     public void setCurrency(String currency){
         this.currency = currency;
     }

     public String getCurrency(){
         return currency;
     }

     public void setSerialNum(String serialNum){
         this.serialNum = serialNum;
     }

     public String getSerialNum(){
         return serialNum;
     }

     public void setDeductionMethod(String deductionMethod){
         this.deductionMethod = deductionMethod;
     }

     public String getDeductionMethod(){
         return deductionMethod;
     }

     public void setDeleted(String deleted){
         this.deleted = deleted;
     }

     public String getDeleted(){
         return deleted;
     }

     public void setCom(String com){
         this.com = com;
     }

     public String getCom(){
         return com;
     }

     public void setSubacc(String subacc){
         this.subacc = subacc;
     }

     public String getSubacc(){
         return subacc;
     }

     public void setLedgerName(String ledgerName){
         this.ledgerName = ledgerName;
     }

     public String getLedgerName(){
         return ledgerName;
     }

     public void setBatchNum(String batchNum){
         this.batchNum = batchNum;
     }

     public String getBatchNum(){
         return batchNum;
     }

     }
