package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_mal_vali_withhold")
public class MalValiWithhold extends BaseDTO {

     public static final String FIELD_MAL_ACCCOUNT_ID = "malAcccountId";
     public static final String FIELD_ACCOUNT_NUMBER = "accountNumber";
     public static final String FIELD_COMPANY_FULLNAME = "companyFullname";


     @Id
     @GeneratedValue
     private Long malAcccountId; //表ID，主键，供其他表做外键

     @Length(max = 200)
     private String accountNumber; //账号

     @Length(max = 200)
     private String companyFullname; //公司名称


     public void setMalAcccountId(Long malAcccountId){
         this.malAcccountId = malAcccountId;
     }

     public Long getMalAcccountId(){
         return malAcccountId;
     }

     public void setAccountNumber(String accountNumber){
         this.accountNumber = accountNumber;
     }

     public String getAccountNumber(){
         return accountNumber;
     }

     public void setCompanyFullname(String companyFullname){
         this.companyFullname = companyFullname;
     }

     public String getCompanyFullname(){
         return companyFullname;
     }

     }
