package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_pub_alix_subcom")
public class PubAlixSubcom extends BaseDTO {

    public static final String FIELD_ALIX_SUBCOM_ID = "alixSubcomId";
    public static final String FIELD_BELONGCOM_NAME = "belongcomName";
    public static final String FIELD_SUBCOM_NAME = "subcomName";
    public static final String FIELD_SUBCOM_VALUE = "subcomValue";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_LEDGER_NAME = "ledgerName";


    @Id
    @GeneratedValue
    private Long alixSubcomId; //表ID，主键，供其他表做外键

    @Length(max = 200)
    private String belongcomName; //所属公司名称

    @Length(max = 200)
    private String subcomName; //分公司名称

    @Length(max = 200)
    private String subcomValue; //分公司段值

    @Length(max = 1)
    private String enabledFlag; //是否有效Y/N

    @Length(max = 200)
    private String ledgerName; //分公司对应分类账


    public void setAlixSubcomId(Long alixSubcomId){
        this.alixSubcomId = alixSubcomId;
    }

    public Long getAlixSubcomId(){
        return alixSubcomId;
    }

    public void setBelongcomName(String belongcomName){
        this.belongcomName = belongcomName;
    }

    public String getBelongcomName(){
        return belongcomName;
    }

    public void setSubcomName(String subcomName){
        this.subcomName = subcomName;
    }

    public String getSubcomName(){
        return subcomName;
    }

    public void setSubcomValue(String subcomValue){
        this.subcomValue = subcomValue;
    }

    public String getSubcomValue(){
        return subcomValue;
    }

    public void setEnabledFlag(String enabledFlag){
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag(){
        return enabledFlag;
    }

    public String getLedgerName() {
        return ledgerName;
    }

    public void setLedgerName(String ledgerName) {
        this.ledgerName = ledgerName;
    }
}
