package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_pub_invoice_entity")
public class PubInvoiceEntity extends BaseDTO {

     public static final String FIELD_INVOICE_ENTITY_ID = "invoiceEntityId";
     public static final String FIELD_INVOICE_ENTITY_NAME = "invoiceEntityName";
     public static final String FIELD_INVOICE_ENTITY_VALUE = "invoiceEntityValue";
     public static final String FIELD_BELONGCOM_NAME = "belongcomName";
     public static final String FIELD_BELONGCOM_VALUE = "belongcomValue";
     public static final String FIELD_LEDGER_NAME = "ledgerName";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";


     @Id
     @GeneratedValue
     private Long invoiceEntityId; //表ID，主键，供其他表做外键

     @Length(max = 200)
     private String invoiceEntityName; //发票主体名称

     @Length(max = 200)
     private String invoiceEntityValue; //发票主体段值

     @Length(max = 200)
     private String belongcomName; //所属公司

     @Length(max = 200)
     private String belongcomValue; //所属公司段值

     @Length(max = 200)
     private String ledgerName; //分类账名称

     @Length(max = 1)
     private String enabledFlag; //是否有效Y/N


     public void setInvoiceEntityId(Long invoiceEntityId){
         this.invoiceEntityId = invoiceEntityId;
     }

     public Long getInvoiceEntityId(){
         return invoiceEntityId;
     }

     public void setInvoiceEntityName(String invoiceEntityName){
         this.invoiceEntityName = invoiceEntityName;
     }

     public String getInvoiceEntityName(){
         return invoiceEntityName;
     }

     public void setInvoiceEntityValue(String invoiceEntityValue){
         this.invoiceEntityValue = invoiceEntityValue;
     }

     public String getInvoiceEntityValue(){
         return invoiceEntityValue;
     }

     public void setBelongcomName(String belongcomName){
         this.belongcomName = belongcomName;
     }

     public String getBelongcomName(){
         return belongcomName;
     }

     public void setBelongcomValue(String belongcomValue){
         this.belongcomValue = belongcomValue;
     }

     public String getBelongcomValue(){
         return belongcomValue;
     }

     public void setLedgerName(String ledgerName){
         this.ledgerName = ledgerName;
     }

     public String getLedgerName(){
         return ledgerName;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     }
