package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_pub_mal_account")
public class PubMalAccount extends BaseDTO {

     public static final String FIELD_MAL_ACCCOUNT_ID = "malAcccountId";
     public static final String FIELD_ABS_NUM = "absNum";
     public static final String FIELD_ACCOUNT_NUM = "accountNum";
     public static final String FIELD_REC_ENTITY = "recEntity";
     public static final String FIELD_REC_COM = "recCom";
     public static final String FIELD_REC_IC = "recIc";
     public static final String FIELD_REC_LEDGER = "recLedger";


     @Id
     @GeneratedValue
     private Long malAcccountId; //表ID，主键，供其他表做外键

     @Length(max = 200)
     private String absNum; //ABS号

     @Length(max = 200)
     private String accountNum; //银行账号

     @Length(max = 200)
     private String recEntity; //收款主体

     @Length(max = 200)
     private String recCom; //收款主体公司段

     @Length(max = 200)
     private String recIc; //收款主体关联方段

     @Length(max = 200)
     private String recLedger; //收款主体分类账


     public void setMalAcccountId(Long malAcccountId){
         this.malAcccountId = malAcccountId;
     }

     public Long getMalAcccountId(){
         return malAcccountId;
     }

     public void setAbsNum(String absNum){
         this.absNum = absNum;
     }

     public String getAbsNum(){
         return absNum;
     }

     public void setAccountNum(String accountNum){
         this.accountNum = accountNum;
     }

     public String getAccountNum(){
         return accountNum;
     }

     public void setRecEntity(String recEntity){
         this.recEntity = recEntity;
     }

     public String getRecEntity(){
         return recEntity;
     }

     public void setRecCom(String recCom){
         this.recCom = recCom;
     }

     public String getRecCom(){
         return recCom;
     }

     public void setRecIc(String recIc){
         this.recIc = recIc;
     }

     public String getRecIc(){
         return recIc;
     }

     public void setRecLedger(String recLedger){
         this.recLedger = recLedger;
     }

     public String getRecLedger(){
         return recLedger;
     }

     }
