package hscsm.core.itf.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "yxhscs_sys_value_set")
public class SysValueSet extends BaseDTO {

     public static final String FIELD_VALUE_SET_ID = "valueSetId";
     public static final String FIELD_VALUE_SET_NAME = "valueSetName";
     public static final String FIELD_VALUE = "value";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";


     @Id
     @GeneratedValue
     private Long valueSetId; //表ID，主键，供其他表做外键

     @Length(max = 200)
     private String valueSetName; //值集名称

     @Length(max = 200)
     private String value; //值

     @Length(max = 200)
     private String description; //说明

     @Length(max = 1)
     private String enabledFlag; //是否有效Y/N


     public void setValueSetId(Long valueSetId){
         this.valueSetId = valueSetId;
     }

     public Long getValueSetId(){
         return valueSetId;
     }

     public void setValueSetName(String valueSetName){
         this.valueSetName = valueSetName;
     }

     public String getValueSetName(){
         return valueSetName;
     }

     public void setValue(String value){
         this.value = value;
     }

     public String getValue(){
         return value;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     }
